services:
  db:
    image: postgres
    container_name: forum-clean-arch
    restart: always
    tty: true
    ports:
      - '5433:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forum-clean-arch